FROM ubuntu:20.04

RUN apt update
RUN apt install -y ca-certificates

RUN useradd -m unityserver

WORKDIR /home/unityserver
USER unityserver

COPY StandaloneLinux64 UnityPlayer.so ./
COPY StandaloneLinux64_Data/ ./StandaloneLinux64_Data/

CMD ["./StandaloneLinux64"]
