name: Game Build
on:
  pull_request:
  release:
    types: [ "published" ]
  push:
    branches:
      - dev
      - test
  workflow_dispatch:

jobs:
  # Phase 1 - Unity Build
  build:
    name: Build game
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2021.3.4f1
        targetPlatform:
          - StandaloneLinux64 # Target build for Linux standalone
          - WebGL # Target build for WebGL
        include:
          - targetPlatform: StandaloneLinux64
            dockerImage: cubespace-server
          - targetPlatform: WebGL
            dockerImage: cubespace-client
    steps:
      # Checkout
      - name: Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      # Restore Cache
      - name: Restore cached Library folder if it exists
        uses: actions/cache@v3
        id: cache-exists
        with:
          path: Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-

      # Generate Library when cache does not exist
      - name: Generate Library folder
        uses: game-ci/unity-builder@v2.1.1
        if: ${{ !steps.cache-exists.outputs.cache-hit && (matrix.targetPlatform == 'StandaloneLinux64') }}
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          buildMethod: UnityBuilderAction.BuildScript.BuildGame
          # If we have custom parameters, add them here with: customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Discard any changes to the working tree caused by generating library
      # TMPro SDF files get auto changed which causes an error when you try to build on the now dirty branch
      #- name: Clear local changes caused by regenerating library and cache
      #  run: |
      #    cd ${GITHUB_WORKSPACE}
      #    git status
      #    git restore *

      # Build
      - name: Build ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2.1.1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          buildMethod: UnityBuilderAction.BuildScript.BuildGame
          # If we have custom parameters, add them here with: customParameters: '-myParameter myValue -myBoolean -ThirdParameter andItsValue'
          # allowDirtyBuild ignores error caused by building with any local changes created by regenerating the local library (TMPro SDF files like to do this)
          #allowDirtyBuild: true
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Upload
      - name: Upload game artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.targetPlatform }} Build
          path: build/${{ matrix.targetPlatform }}

      # Phase 2 - Docker Containerization
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cmusei/${{ matrix.dockerImage }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./build/${{ matrix.targetPlatform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile.${{ matrix.targetPlatform }}

      - name: Cleanup Docker System
        run: docker system prune -a -f
